### ISSUE TITLE
Mulitple Listeners example not working

### ISSUE THREAD

**Issue by nickwales** [rhoml/puppet-vault#5]
### Expected behavior

The multiple listener hiera example should create two listener stanza's

### Actual behavior

`  "listener": [
    {
      "tcp": {
        "address": "127.0.0.1:8200",
        "tls_disable": true
      }
    },
    {
      "tcp": {
        "address": "<fqdn>:8200",
        "tls_cert_file": "/path/to/cert",
        "tls_key_file": "/path/to/key"
      }
    }
  ],`

It creates an array, which vault 0.6.2 rejects with the following:

> Error loading configuration from /etc/vault/vault.json: error parsing 'listener': listeners.tcp: At -: root.tls_disable: unknown type for string *ast.LiteralType

**Comment by rhoml** [comment]
Hey thanks for using puppet-vault will check this error today

**Comment by nickwales** [comment]
Sure thing, thanks for getting back to me so quickly. 

```
vault::config_hash:
    backend:
        consul:
            address: '127.0.0.1:8500'
            advertise_addr: "https://%{::fqdn}:8200"
            path: 'vault/'
    listener:
        - tcp:
            address: "127.0.0.1:8200"
            tls_disable: true
        - tcp:
            address: "%{::fqdn}:8200"
            tls_cert_file: "/etc/ssl/certs/vault.crt"
            tls_key_file:  "/etc/ssl/certs/vault.key"

    telemetry:
        statsd_address: '127.0.0.1:8125'
    disable_mlock: true
vault::manage_user: true
vault::package_ensure: 'present'
vault::vault_user: 'vault'
vault::restart_cmd: '/etc/init.d/vault restart'
```

**Comment by rhoml** [comment]
can you please try the following

```yaml
vault::config_hash:
    backend:
        consul:
            address: '127.0.0.1:8500'
            advertise_addr: "https://%{::fqdn}:8200"
            path: 'vault/'
    listener:
        tcp:
          address: "127.0.0.1:8200"
          tls_disable: true
        tcp:
          address: "%{::fqdn}:8200"
          tls_cert_file: "/etc/ssl/certs/vault.crt"
          tls_key_file:  "/etc/ssl/certs/vault.key"

    telemetry:
        statsd_address: '127.0.0.1:8125'
    disable_mlock: true
vault::manage_user: true
vault::package_ensure: 'present'
vault::vault_user: 'vault'
vault::restart_cmd: '/etc/init.d/vault restart'
```
